# Generated by Django 4.0.5 on 2022-06-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_products_is_top_selling'),
    ]

    operations = [
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_image',
        ),
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ManyToManyField(to='product.productimage'),
        ),
    ]
