# Generated by Django 4.0.5 on 2022-06-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productimage_remove_products_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='productColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('Grey', 'Grey'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='productSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_color',
            field=models.ManyToManyField(to='product.productcolor'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_size',
            field=models.ManyToManyField(to='product.productsize'),
        ),
    ]
