# Generated by Django 4.0.5 on 2022-06-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcolor_productsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='product_size',
            field=models.CharField(max_length=150),
        ),
    ]
