# Generated by Django 4.0.5 on 2022-06-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_wishitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(to='product.wishitem'),
        ),
    ]
