# Generated by Django 4.0.5 on 2022-06-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userdetails_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremail',
            name='has_data',
        ),
        migrations.AddField(
            model_name='useremail',
            name='address',
            field=models.CharField(max_length=80, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='useremail',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=20, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='useremail',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='useremail',
            name='phone',
            field=models.PositiveBigIntegerField(null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='useremail',
            name='user_image',
            field=models.ImageField(default='user.jpg', upload_to='user_image/'),
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
