# Generated by Django 4.0.5 on 2022-06-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_useremail_has_data_useremail_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='user_image',
            field=models.ImageField(default='user_image/user.jpg', upload_to='user_image/'),
        ),
    ]
