# Generated by Django 4.0.5 on 2022-06-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_useremail_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=20, null=True, verbose_name='Gender'),
        ),
    ]
