# Generated by Django 4.0.5 on 2022-06-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_useremail_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='user_image/'),
        ),
    ]
