# Generated by Django 4.0.5 on 2022-06-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('current_order', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='order_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=150)),
                ('payment_by', models.PositiveBigIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('order_code', models.CharField(max_length=10)),
                ('payment_token', models.CharField(max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=10)),
                ('order_date', models.DateField()),
                ('order_end', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('item', models.ManyToManyField(to='order.items')),
            ],
        ),
    ]
