# Generated by Django 4.0.5 on 2022-06-15 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField( max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.PositiveBigIntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='drop_location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order_payment',
            name='payment_token',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
