# Generated by Django 4.0.5 on 2022-06-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_location_email_location_name_location_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_number', models.CharField(max_length=8)),
                ('discount', models.PositiveSmallIntegerField()),
                ('generated_date', models.DateTimeField(auto_now=True)),
                ('is_Expired', models.BooleanField(default=False)),
            ],
        ),
    ]
