# Generated by Django 4.0.5 on 2022-06-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
