# Generated by Django 4.0.5 on 2022-06-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_items_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
