# Generated by Django 4.0.5 on 2022-06-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orders_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_color',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='item_size',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
