# Generated by Django 4.0.5 on 2022-06-20 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_items_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='drop_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.location'),
        ),
    ]
