# Generated by Django 4.0.5 on 2022-06-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_location_order_orders_drop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_payment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
