# Generated by Django 4.0.5 on 2022-06-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_items_current_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='current_order',
            field=models.BooleanField(default=False),
        ),
    ]
